### ISSUE TITLE
1.0.0 version

### ISSUE THREAD

**Issue by mcollina** [mcollina/ascoltatori#63]
I am think about releasing a 1.0.0 version to stabilize each Ascoltatore API.
I think it is fairly stable right now.

What I would like to include:
* [x] EE2Ascoltatore #61.
* [x] Single level wildcards #62.
* [x] remove newTopic #60.
* [x] remove while iterating #56.
* [ ] Define in the README the Ascoltatore API, mainly `publish`, `subscribe` and `close`.
* [x] Define in the README the configuration options #64.
* [x] Code coverage #67.
